package taobao

import (
	"context"
	"os"
	"strings"
	"testing"

	"github.com/go-marvis/taobao-sdk-go/core"
	"github.com/go-marvis/taobao-sdk-go/service/taobao/trade/fullinfo"
	"github.com/go-marvis/taobao-sdk-go/service/taobao/trades/sold"
	"github.com/stretchr/testify/assert"
)

var (
	api = NewClient(&core.Config{
		AppKey:     os.Getenv("APP_KEY"),
		Secret:     os.Getenv("SECRET"),
		BaseUrl:    "https://eco.taobao.com/router/rest",
		SignMethod: core.MD5,
		Format:     core.JSON,
		Version:    "2.0",
		Session:    os.Getenv("SESSION"),
		Debug:      true,
		Retry:      2,
	})
)

func Test_TaobaoTradeFullInfoGet(t *testing.T) {
	ctx := context.Background()
	resp, err := api.Taobao.Trade.Fullinfo.Get(ctx, fullinfo.NewGetReqBuilder().
		Fields("tid,type,status,payment,orders,rx_audit_status").
		Tid(2590044351089921152).
		Build())
	assert.Nil(t, err)
	assert.NotNil(t, resp.Trade)
}

func Test_TaobaoTradesSoldGet(t *testing.T) {
	ctx := context.Background()
	fields := []string{
		"orders",
		"promotion_details",
		"service_tags",
		"service_orders",
		"logistics_infos",
		"step_pay_details",
		"agree_refund_checks",
		"address_details",
		"delivery_plan",
		"combine_logistics_details",
		"logistics_consign_info",
		"logistics_modify_info",
		"receipt_rel_ids",
		"modified",
		"buyer_open_uid",
		"title",
		"type",
		"created",
		"sid",
		"acookie_id",
		"status",
		"payment",
		"discount_fee",
		"adjust_fee",
		"post_fee",
		"total_fee",
		"pay_time",
		"end_time",
		"consign_time",
		"received_payment",
		"commission_fee",
		"buyer_memo",
		"seller_memo",
		"buyer_area",
		"alipay_no",
		"buyer_message",
		"pic_path",
		"price",
		"cod_fee",
		"cod_status",
		"buyer_cod_fee",
		"seller_cod_fee",
		"express_agency_fee",
		"shipping_type",
		"buyer_alipay_no",
		"receiver_name",
		"receiver_country",
		"receiver_state",
		"receiver_city",
		"receiver_district",
		"receiver_town",
		"receiver_address",
		"receiver_zip",
		"receiver_mobile",
		"receiver_phone",
		"buyer_email",
		"seller_alipay_no",
		"seller_mobile",
		"seller_phone",
		"seller_name",
		"seller_email",
		"available_confirm_fee",
		"timeout_action_time",
		"snapshot_url",
		"trade_memo",
		"promotion",
		"credit_card_fee",
		"step_trade_status",
		"step_paid_fee",
		"eticket_ext",
		"mark_desc",
		"yfx_fee",
		"yfx_id",
		"yfx_type",
		"send_time",
		"arrive_cut_time",
		"o2o",
		"o2o_guide_id",
		"o2o_guide_name",
		"o2o_shop_id",
		"o2o_shop_name",
		"o2o_delivery",
		"o2o_out_trade_id",
		"shop_code",
		"hk_en_name",
		"hk_flight_no",
		"hk_china_name",
		"hk_card_code",
		"hk_card_type",
		"hk_flight_date",
		"hk_gender",
		"hk_birthday",
		"hk_pickup",
		"hk_pickup_id",
		"est_con_time",
		"trade_from",
		"trade_source",
		"order_tax_fee",
		"et_ser_time",
		"et_shop_name",
		"et_verified_shop_name",
		"et_plate_number",
		"o2o_snatch_status",
		"eticket_service_addr",
		"et_type",
		"market",
		"obs",
		"paid_coupon_fee",
		"shop_pick",
		"rx_audit_status",
		"es_date",
		"es_range",
		"os_date",
		"os_range",
		"trade_attr",
		"omni_attr",
		"omni_param",
		"assembly",
		"identity",
		"o2o_step_trade_detail",
		"o2o_step_order_id",
		"o2o_et_order_id",
		"o2o_voucher_price",
		"order_tax_promotion_fee",
		"tid_str",
		"service_type",
		"o2o_service_mobile",
		"o2o_service_name",
		"o2o_service_state",
		"o2o_service_city",
		"o2o_service_district",
		"o2o_service_town",
		"o2o_service_address",
		"o2o_step_trade_detail_new",
		"o2o_xiaopiao",
		"o2o_contract",
		"recharge_fee",
		"retail_store_code",
		"retail_out_order_id",
		"platform_subsidy_fee",
		"nr_offline",
		"wtt_param",
		"seller_nick",
		"buyer_nick",
		"nr_store_order_id",
		"nr_shop_id",
		"nr_shop_name",
		"nr_shop_guide_id",
		"nr_shop_guide_name",
		"nr_no_handle",
		"biz_code",
		"cloud_store",
		"donee_nick",
		"donee_open_uid",
		"suning_shop_code",
		"allow_appkeys",
		"retail_store_id",
		"ua",
		"linkedmall_ext_info",
		"pay_channel",
		"rt_omni_send_type",
		"rt_omni_store_id",
		"rt_omni_outer_store_id",
		"tcps_start",
		"tcps_code",
		"tcps_end",
		"m_tariff_fee",
		"timing_promise",
		"promise_service",
		"cutoff_minutes",
		"es_time",
		"delivery_time",
		"collect_time",
		"dispatch_time",
		"sign_time",
		"outer_partner_member_id",
		"root_cat",
		"gifting",
		"gifting_takeout",
		"oi_date",
		"oi_range",
		"hold_install",
		"app_name",
		"easy_home_city_type",
		"nr_deposit_order_id",
		"nr_store_code",
		"propoint",
		"zqs_order_tag",
		"txp_freezer_id",
		"txp_receive_method",
		"extend_info",
		"lm",
		"brand_light_shop_source",
		"brand_light_shop_store_id",
		"is_wmly",
		"omni_package",
		"ncz_ext_attr",
		"invoice_detail_pay",
		"invoice_detail_mid_refund",
		"invoice_detail_after_refund",
		"expand_card_basic_price",
		"expand_card_expand_price",
		"expand_card_basic_price_used",
		"expand_card_expand_price_used",
		"delivery_cps",
		"asdp_biz_type",
		"order_follow_id",
		"asdp_ads",
		"ob_tag",
		"drug_register",
		"stage_address_type",
		"og_id",
		"promise_sign_time",
		"omnichannel_param",
		"oaid",
		"scenario_group",
		"play_type",
		"priority_consign_time",
		"real_name_auth_status",
		"third_party_customs_declaration",
		"receipt_type",
		"async_modified",
		"nut_feature",
		"lg_aging_type",
		"lg_aging",
		"cn_service",
		"aid",
		"tid",
		"num_iid",
		"num",
		"point_fee",
		"real_point_fee",
		"buyer_obtain_point_fee",
		"buyer_flag",
		"seller_flag",
		"arrive_interval",
		"consign_interval",
		"alipay_point",
		"pcc_af",
		"trade_ext",
		"et_shop_id",
		"coupon_fee",
		"top_hold",
		"forbid_consign",
		"team_buy_hold",
		"share_group_hold",
		"ofp_hold",
		"delay_create_delivery",
		"toptype",
		"sort_info",
		"sorted",
		"suning_shop_valid",
		"expandcard_info",
		"tmall_coupon_fee",
		"identify_info",
		"logistics_agreement",
		"alipay_id",
		"seller_rate",
		"buyer_rate",
		"has_post_fee",
		"is_3D",
		"is_lgtype",
		"is_brand_sale",
		"is_force_wlb",
		"has_yfx",
		"can_rate",
		"seller_can_rate",
		"is_part_consign",
		"is_daixiao",
		"is_wt",
		"zero_purchase",
		"is_sh_ship",
		"post_gate_declare",
		"cross_bonded_declare",
		"is_gift",
		"new_presell",
		"you_xiang",
		"is_istore",
		"is_openmall",
		"v_logistics_create",
		"q_r_pay",
		"general_new_presell",
		"is_cycle_buy",
		"is_force_dc",
		"has_buyer_message",
		"is_o2o_passport",
		"tmall_delivery",
		"threepl_timing",
		"no_shipping",
	}
	resp, err := api.Taobao.Trades.Sold.Get(ctx, sold.NewGetReqBuilder().
		PageNo(0).PageSize(1).
		Fields(strings.Join(fields, ",")).
		StartCreated("2025-06-01 10:00:00").
		EndCreated("2025-06-01 12:00:00").
		Build())
	assert.Nil(t, err)
	t.Log(len(resp.Trades))
	assert.True(t, len(resp.Trades) > 0)
}

func Test_TaobaoTradesSoldGetIncrement(t *testing.T) {
	ctx := context.Background()
	resp, err := api.Taobao.Trades.Sold.IncrementGet(ctx, (*sold.IncrementGetReq)(sold.NewIncrementGetReqBuilder().
		PageNo(0).PageSize(1).
		Fields("tid,type,status").
		StartModified("2025-08-01 10:00:00").
		EndModified("2025-08-01 14:00:00").
		Build()))
	assert.Nil(t, err)
	t.Log(len(resp.Trades))
	assert.True(t, len(resp.Trades) > 0)
}
